#pragma config(Motor,  motorA,          foo,           tmotorNXT, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[foo] = 50;

	wait1Msec(2000);
}
