#pragma config(Sensor, S1,     distance,       sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     button,         sensorEV3_Touch)
#pragma config(Motor,  motorA,          foo,           tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[foo] = 100;
	wait1Msec(2000);
	motor[foo] = 0;
	while (true){
		if (getTouchValue(S2)){
			motor[foo] = 100;
		} else {
			motor[foo] = 0;
		}
	}
}
